# Generated by Django 5.0.4 on 2024-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('poster', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
