# Generated by Django 5.0.4 on 2024-05-21 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Director', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='birth_place',
            new_name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='director',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='director',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='director',
            name='poster',
        ),
        migrations.AddField(
            model_name='director',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='deathday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='director/'),
        ),
        migrations.CreateModel(
            name='DirectorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='director/')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Director.director')),
            ],
        ),
    ]
