# Generated by Django 5.0.4 on 2024-05-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Director", "0002_rename_birth_place_director_place_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="name",
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name="director",
            name="place_of_birth",
            field=models.TextField(max_length=50),
        ),
    ]
