# Generated by Django 5.0.4 on 2024-05-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Director", "0004_alter_director_name_alter_director_place_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
