# Generated by Django 5.0.4 on 2024-05-25 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Director", "0005_alter_director_place_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="director",
            name="image",
        ),
    ]
