# Generated by Django 5.0.4 on 2024-06-27 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Director", "0006_remove_director_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directorimage",
            name="director",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="director_images",
                to="Director.director",
            ),
        ),
    ]
