# Generated by Django 5.0.4 on 2024-06-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actor', '0002_rename_first_name_actor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
        migrations.AlterField(
            model_name='actor',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
