# Generated by Django 5.0.4 on 2024-06-17 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Actor", "0003_remove_actor_image_alter_actor_place_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actorimage",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actor_images",
                to="Actor.actor",
            ),
        ),
    ]
