# Generated by Django 5.0.4 on 2024-06-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Rate", "0002_alter_rate_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
