# Generated by Django 5.0.4 on 2024-05-21 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_movie_budget_movie_original_country_movie_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie/')),
                ('type', models.CharField(choices=[('backdrops', 'backdrops'), ('posters', 'posters'), ('logos', 'logos')], max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.FileField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(choices=[('Trailers', 'Trailers'), ('Teasers', 'Teasers'), ('Clips', 'Clips'), ('Behind the Scene', 'Behind the Scene'), ('Bloopers', 'Bloopers'), ('Featurettes', 'Featurettes'), ('Opening Credits', 'Opening Credits')], max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Trailer',
        ),
    ]
