# Generated by Django 5.0.4 on 2024-04-24 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_movie_poster_movie_summary_movie_synopsis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rate',
            new_name='ave_rate',
        ),
    ]
