# Generated by Django 5.0.4 on 2024-05-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_remove_trailer_movie_alter_movie_synopsis_movieimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='type',
            field=models.CharField(choices=[('backdrops', 'backdrop'), ('posters', 'poster'), ('logos', 'logo')], max_length=20),
        ),
    ]
