# Generated by Django 5.0.4 on 2024-06-04 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Movie", "0005_remove_movie_actors_remove_movie_genres_movie_actor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie_actor",
            old_name="character",
            new_name="character_name",
        ),
    ]
