# Generated by Django 5.0.4 on 2024-06-14 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Director', '0006_remove_director_image'),
        ('Movie', '0006_rename_character_movie_actor_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='Director.director'),
        ),
        migrations.AlterField(
            model_name='movie_genre',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genre', to='Movie.movie'),
        ),
        migrations.AlterField(
            model_name='movieimage',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieimage_set', to='Movie.movie'),
        ),
    ]
