# Generated by Django 5.0.4 on 2024-06-22 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Actor", "0004_alter_actorimage_actor"),
        ("Movie", "0008_alter_movie_director_alter_movie_actor_movie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie_actor",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actor_movie",
                to="Actor.actor",
            ),
        ),
        migrations.AlterField(
            model_name="movievideo",
            name="type",
            field=models.CharField(
                choices=[
                    ("Trailer", "Trailer"),
                    ("Teaser", "Teaser"),
                    ("Clip", "Clip"),
                    ("Behind the Scenes", "Behind the Scenes"),
                    ("Blooper", "Blooper"),
                    ("Featurette", "Featurette"),
                    ("Opening Credits", "Opening Credits"),
                ],
                max_length=20,
            ),
        ),
    ]
