# Generated by Django 5.0.4 on 2024-07-01 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Review", "0004_remove_review_num_vote_down_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="timestamp",
        ),
    ]
