# Generated by Django 5.0.4 on 2024-06-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profile", "0004_alter_profile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
